### ISSUE TITLE
Move SaveData

### ISSUE THREAD

**Issue by liaochris** [JMSLab/Template#102]
Move SaveData.py gslab-econ/gslab_python to JMSLab/TemplatePer lab meeting, use as application in https://github.com/JMSLab/Template/blob/main/source/derived/wb_clean/build.py

**Comment by liaochris** [comment]
@jmshapir I need write access to the repo in order to create a development branch. Thanks!

**Comment by jmshapir** [comment]
@liaochris should be done thanks!

**Comment by liaochris** [comment]
In this issue, we migrated `SaveData.py` and associated dependencies from `gslab-econ/gslab_python` to `JMSLab/Template`. Here's a list of the important changes
- `SaveData.py` new home: [`source/lib/JMSLab/SaveData.py`](https://github.com/JMSLab/Template/blob/1184747f95523c4c2dcf3564ee1efc9ddf67f2d9/source/lib/JMSLab/SaveData.py)
- Implementation of `SaveData` in [`source/derived/wb_clean/build.py`](https://github.com/JMSLab/Template/blob/1184747f95523c4c2dcf3564ee1efc9ddf67f2d9/source/derived/wb_clean/build.py)
- Unit tests`test_savedata.py` and `data/data.csv` in the [`tests`](https://github.com/JMSLab/Template/tree/1184747f95523c4c2dcf3564ee1efc9ddf67f2d9/source/lib/JMSLab/tests) folder
- Updated [Github Actions workflow](https://github.com/JMSLab/Template/blob/1184747f95523c4c2dcf3564ee1efc9ddf67f2d9/.github/workflows/pytest.yml) to test Python 3.9-3.11 instead of Python 3.8-3.10

Latest version of issue branch prior to merge: 1184747f95523c4c2dcf3564ee1efc9ddf67f2d9
Branch merged to master in https://github.com/JMSLab/Template/commit/136f43826d79ebe8780d01ed26a966a130ab8a42
