### ISSUE TITLE
Updates python instructions in readme

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/Template#104]

**Comment by liaochris** [comment]
In this issue, we updated python instructions in [`README.md`](https://github.com/JMSLab/Template/blob/a8ba204f2568a6ad032b93970a4aecd6774bb04d/README.md) to reflect the fact that we no longer support python 3.8. 

Latest version of issue branch: a8ba204f2568a6ad032b93970a4aecd6774bb04d
Branch merged in https://github.com/JMSLab/Template/commit/86efbe16cfc5797c3245ca4b3e9e903a574696a5
