### ISSUE TITLE
Avoid potential name conflict in MATLAB plotting

### ISSUE THREAD

**Issue by ew487** [JMSLab/Template#63]
In this issue we will address this warning from `output/analysis/plots/sconscript.log`:

![image](https://user-images.githubusercontent.com/108754119/181132097-33bc09cc-9ba4-4f6a-b9cc-c7512c043203.png)

@rcalvo12 @ew487 can we open a new issue to address the point raised in this warning? Thanks!

_Originally posted by @jmshapir in https://github.com/JMSLab/Template/pull/62#discussion_r928911571_

**Comment by rcalvo12** [comment]
Addressed in https://github.com/JMSLab/Template/pull/56/commits/0d23e839d192811861a3db6ec4a489900e846e56 as part of issue #42.
