### ISSUE TITLE
Stray rscript.log

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/Template#69]
@rcalvo12 @ew487 am I right that the file [here](https://github.com/JMSLab/Template/blob/8236cfde2884e945cb5758f6b8b40264bcf8a4c7/rscript.log) is an accidental commit?

If so I'll go ahead and remove it, thanks!

**Comment by rcalvo12** [comment]
Thanks @jmshapir, Yes, this looks like an accidental commit! I don't think we ever use rscript.log files.

**Comment by jmshapir** [comment]
Summary: In this issue we deleted a [stray file](https://github.com/JMSLab/Template/issues/69#issue-1424035188). Changes brought to `main` in [26a8a8e](https://github.com/JMSLab/Template/commit/26a8a8e6bc649553ff66d2a65eda30adca1e8111).
