### ISSUE TITLE
Make gitattributes caps-agnostic

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/Template#74]
Steps:
- [x] Confirm that [`gitattributes`](https://github.com/JMSLab/Template/blob/b9bae5dc3b7d250079deef55790e0e3e2b9edae3/.gitattributes) is case-sensitive
- [x] If so, update [`gitattributes`](https://github.com/JMSLab/Template/blob/b9bae5dc3b7d250079deef55790e0e3e2b9edae3/.gitattributes) to include the possible capitalizations of the `RDS` extension (and any other extensions we think might plausibly be saved with multiple capitalizations in the extension)

**Comment by jmshapir** [comment]
@rcalvo12 @ew487 fyi. Feel free to self-assign when you have some bandwidth.

**Comment by rcalvo12** [comment]
@jmshapir after looking around the documentation/ forum posts, and considering our experience, it seems like `.gitattributes` is indeed case sensitive. I added alternate capitalizations to `.gitattributes` in https://github.com/JMSLab/Template/commit/1f9136869461c5b65815939f55af46d980eac69a.

**Comment by jmshapir** [comment]
@rcalvo12 thanks! Can you open a pull with @jmshapir as reviewer? It should be quick. :-)

**Comment by rcalvo12** [comment]
Thread continues in #75.

**Comment by rcalvo12** [comment]
**Summary:** 

In this issue we confirmed that `.gitattributes` is case-sensitive and then updated `.gitattributes` to include alternate capitalizations.

Merged in https://github.com/JMSLab/Template/commit/d39df7414aad471b3df214f6684191496b2a90fd.
Final state of issue branch [here](https://github.com/JMSLab/Template/tree/1f9136869461c5b65815939f55af46d980eac69a).
