### ISSUE TITLE
Add LaTeX template for slides

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/Template#88]
@ew487 can we:
- [ ] add a LaTeX file with a very basic beamer shell (from a public source) for slides to [`/source/talk`](https://github.com/JMSLab/Template/tree/204def9224fc4259dad68c77a04aa190fe008291/source/talk) in which we:
   - [ ] enable the option [`\setbeameroption{hide notes}`](https://tug.ctan.org/macros/latex/contrib/beamer/doc/beameruserguide.pdf#198) by default
   - [ ] add an example in-frame speaker note to one of the slide frames
- [ ] add to the LaTeX builder a `handout` option similar to the one we have for LyX
   * under the hood, all this should need to do is switch `hide notes` to `show notes`

Thanks!

**Comment by ew487** [comment]
@jmshapir Do you happen to remember how you resolved the issue from [here](https://github.com/JMSLab/Template/issues/85#issuecomment-1781908760)? I'm running into the same problem!

**Comment by jmshapir** [comment]
@ew487 I think (?) I was able to resolve that by first compiling locally using a GUI and then via `scons`. (It might also have just been out of date packages.)

If that's not working for you you can feel free to comment out the EPS call and flag it for me to look at when everything else is set up here.

Thanks!

**Comment by ew487** [comment]
@jmshapir Thanks for letting me know! Unfortunately I was still not able to get it to work, but it does work on my other computer so I will just use that instead.

In the last commit I added most of the functionality you asked for. I was wondering, what do you think about using `\todo` rather than `\note`? That way the notes will show up on the same page as the slides, like they do for the lyx documents, rather than on their own page.

**Comment by jmshapir** [comment]
@ew487 thanks! Can you show me how `\todo` vs. `\note` look in the compiled PDF for an example?

**Comment by ew487** [comment]
@jmshapir Yep! [Here](https://github.com/JMSLab/Template/files/13689063/TemplateLatex.handout.todo.pdf) is the version with todo, and [here](https://github.com/JMSLab/Template/files/13689062/TemplateLatex.handout.note.pdf) is the version with note.

**Comment by jmshapir** [comment]
@ew487 thanks!

Let's go with `\note`.

Once everything is set up feel free to open a pull with @jmshapir as reviewer and I can take a first pass.

**Comment by ew487** [comment]
Thread continues in its pull request #89

**Comment by ew487** [comment]
**Summary**

[Link](https://github.com/JMSLab/Template/tree/361a934601158cd07fe9580faac97fe5d55fb65f) to issue branch
Merged to master [here](https://github.com/JMSLab/Template/commit/c36e8538f5358980efb9f2f4690710fa1b953d86)

In this issue, we added a LaTeX file with a basic beamer shell for slides to [/source/talk] in which we enable the option `\setbeameroption{hide notes}` by default. We added to the LaTeX builder a handout option similar to the one we have for LyX
under the hood, which switches `hide notes` to `show notes`. We also added unit testing for this option.
