### ISSUE TITLE
fix typo

### ISSUE THREAD

**Issue by zhizhongpu** [JMSLab/Template#94]
Fix typos in source/lib/JMSLab/tablefill_info.py per https://github.com/JMSLab/Protests/pull/796#discussion_r1532532829

**Comment by jmshapir** [comment]
> @jmshapir please grant me authorizations to assign an open a branch - thank you

@zhizhongpu done, use it wisely, thanks!

> also, is there a reason why source/lib/JMSLab/tablefill_info.py is a python script instead of a .md?

Looks to me like it's designed as a docstring:

https://github.com/JMSLab/Template/blob/466a62f9b99159f19c99984aec9a6af1b140389d/source/lib/JMSLab/tablefill.py#L6


https://github.com/JMSLab/Template/blob/466a62f9b99159f19c99984aec9a6af1b140389d/source/lib/JMSLab/tablefill.py#L26-L27
